### ISSUE TITLE
uBlock Origin 1.28.5b2 interfere with custom styles of TST

### ISSUE THREAD

**Issue by Altsinn** [uBlockOrigin/uBlock-issues#1167]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

https://github.com/piroor/treestyletab/issues/2651

### A specific URL where the issue occurs

Any web page except Firefox internal ones.

### Steps to Reproduce

1. Instal uBlock Origin 1.28.5b2
2. Instal TST 3.5.12
3. Apply custom style for discarded tabs in TST advanced settings:

```
/* Change styling of pending (unloaded) tabs */

.tab.discarded
{
	filter: grayscale(70%);
    transition: filter 0.2s ease-in;
    opacity: 0.7;
    font-style: italic !important;
}
```

![obraz](https://user-images.githubusercontent.com/50676021/87873563-eae5f980-c9c2-11ea-981f-1291763693e9.png)

3. Restart Firefox or use "Restore previous session"

### Expected behavior:

Custom user style is applied for all tabs

### Actual behavior:

Custom user style is applied for internal pages only

### Your environment

* uBlock Origin version: 1.28.5b2 
* Browser Name and version: FX 68 ESR (tested also on FX78 ESR and FX Nightly 80.0a1
* Operating System and version: Windows 7

**Comment by uBlock-user** [comment]
> Custom user style is applied for internal pages only

Userstyle is not getting applied anywhere on my end.

**Comment by gorhill** [comment]
uBO can't act on other extensions's page, as per WebExtensions API limitations.

**Comment by uBlock-user** [comment]
dev also addressed it -- https://github.com/piroor/treestyletab/issues/2651#issuecomment-660616755

**Comment by gorhill** [comment]
> I disabled them one by one and I found the culprit - uBlock Origin 1.28.5b2

I suspect you are suffering a timing issue in TST, and you too quickly concluded uBO is your issue.

**Comment by gwarser** [comment]
Bisection shows feabfe379331c6e4366e104e36c41a4e88221733

**Comment by Altsinn** [comment]
> I suspect you are suffering a timing issue in TST, and you too quickly concluded uBO is your issue.

I respectfully disagree. After I narrowed down the potential culprit to uBO 1.28.5b2, I tested this on Fx68, Fx78 and Nightly 80a. No other add-ons, just uBO enabled. With 1.28.5b1 or earlier everything works fine. I think @uBlock-user was able to reproduce.

>Userstyle is not getting applied anywhere on my end.

On Nigthly I got the same results - userstyle was not applied even for internal pages.

**Comment by uBlock-user** [comment]
What I produced is the said extension failing to work with or without uBO.

**Comment by gorhill** [comment]
I find surprising that uBO can have an effect on another extension's page, this is forbidden by the WebExtensions API. While testing the code pointed out by @gwarser, I did find an issue this uBO's new code which I will fix for next dev build. However I think more investigation is needed to find out whether there is something unexpected with the WebExtensions framework.

**Comment by gorhill** [comment]
@gwarser Are you saying my change fixed the issue?

**Comment by gwarser** [comment]
Yes, I tried it already in custom build.

**Comment by gorhill** [comment]
Well then something is wrong with the WebExtensions API, uBO is merely calling [webNavigation.getAllFrames](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webNavigation/getAllFrames) without trying to modify anything. The issue I fixed in uBO is that it was calling getAllFrames() earlier than intended.

**Comment by Altsinn** [comment]
I tested the latest build 1.28.5b3 and this issue is not preset any more. Thanks for the quick fix!

**Comment by uBlock-user** [comment]
@Altsinn The issue still exists, just not with uBO anymore.

**Comment by jspenguin2017** [comment]
It's a Firefox bug, calling `getAllFrames` wakes up the tab: https://bugzilla.mozilla.org/show_bug.cgi?id=1428956

**Comment by gwarser** [comment]
Then maybe it's not really fixed, uBO is now waiting for more frames on startup - `frameAddCount` is no longer `NaN`.

**Comment by gorhill** [comment]
If the tab is suspended than no subframe should be reported for it and thus pruneFrames() will never be called for the tab, hence the tab won't be unsuspended.
