### ISSUE TITLE
Fetch API in service worker fails on homepage even with domain whitelisted

### ISSUE THREAD

**Issue by chrisblakley** [uBlockOrigin/uBlock-issues#173]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings *(I apologize I don't know how to do this- I believe I just use the default settings and I never mess with the lists)*
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I began noticing in Chrome 67 and 68 that the Fetch API inside my service worker file is successfully loading other resources on my website, but fails (without additional context to the error message- only "Failed to fetch") when attempting to load the home page. When reloading, it attempts to load the home page via Fetch API and when it fails, it delivers the cached offline page (if available) or the browser's network connection error page. This happens even though uBlock Origin is set to whitelist this domain.

**More information:**
- [My Github repo](https://github.com/chrisblakley/Nebula/issues/1709)
- [Stack Overflow](https://stackoverflow.com/questions/51833056/fetch-api-inside-service-worker-fails-only-for-the-home-page-when-reloading-it)
- [Chromium Bug Tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=874173)

For reference, here is the fetch test case I wrote in my service worker JavaScript file.
```js
console.log('(A) about to fetch via sw');
fetch('https://gearside.com/nebula/get-started/checklists/').then(function(response) {
	console.log('(A) we got it!', response);
}).then(function(returnedValue) {
	console.log('(A) returning the value!', returnedValue);
}).catch(function(err) {
	console.log('(A) fetch error:', err);
});

console.log('(B) about to fetch via sw');
fetch('https://gearside.com/nebula/').then(function(response) {
	console.log('(B) we got it!', response);
}).then(function(returnedValue) {
	console.log('(B) returning the value!', returnedValue);
}).catch(function(err) {
	console.log('(B) fetch error:', err);
});
```

When uBlock Origin is not installed or completely disabled both fetches will work successfully. However, if it is active (even if the domain is whitelisted) fetch `(B)` will fail.

### A specific URL where the issue occurs

https://gearside.com/nebula/

### Steps to Reproduce

1. Load the above URL and open the JavaScript console
2. View the console to see two fetches `(A)` and `(B)`. `(A)` successfully fetches a subpage whereas `(B)` fails to fetch the home page.
3. Simple reload will show the network connection error page (or the cached offline page)

### Expected behavior:

The console will show both fetches successful. A reload will load the cached homepage (or successfully request from the network).

<img width="540" alt="44207948-f6707c00-a12c-11e8-853b-ac5e8bcde075" src="https://user-images.githubusercontent.com/6349678/44209707-41d95900-a132-11e8-9c75-b5ef2bed72e7.png">

### Actual behavior:

`(A)` successfully fetches a subpage whereas `(B)` fails to fetch the home page. Reloading the page will trigger a fetch error and show the network connection error page or the cached offline page.

![43363092-724a1a5a-92ca-11e8-8330-dca660e06b6f](https://user-images.githubusercontent.com/6349678/44209713-46057680-a132-11e8-9de0-771b11ec2229.png)

Showing uBlock Origin is active but whitelisted:
![screen shot 2018-08-16 at 8 57 53 am](https://user-images.githubusercontent.com/6349678/44209807-8e249900-a132-11e8-8a87-d52cf0b10a07.png)

### Your environment

* uBlock Origin version: 1.16.14
* Browser Name and version: Chrome 68.0.3440.106
* Operating System and version: MacOS 10.13.6

**Comment by uBlock-user** [comment]
![](https://i.gyazo.com/70d1a4008afce6db5888e82a07d4b9da.png)

**Comment by gorhill** [comment]
Unable to reproduce as per repro steps. Using default lists/settings. Likely a filter issue, please always use uBO's logger to rule out filter issues.

**Comment by uBlock-user** [comment]
Most likely a filter list issue, check the logger if an `first-party` resource or if any resource from `cloudflare.com` is blocked.

**Comment by chrisblakley** [comment]
I do see a blocked entry in the logger, but (and maybe I'm misunderstanding how uBlock is meant to work) if the website I am on is whitelisted, aren't all requests on that site also whitelisted? As in, if I "Click to disable uBlock on this site" shouldn't the filters not be involved?

<img width="1051" alt="screen shot 2018-08-16 at 10 08 35 am" src="https://user-images.githubusercontent.com/6349678/44213911-df398a80-a13c-11e8-87fe-5562992595f6.png">

I thought that maybe there was a bug in the whitelist because of the service worker making the fetch request (and not necessarily the website). Is there a way to whitelist a service worker as well as a website?

I do see your screenshot above which definitely shows it working fine, so I guess my confusion is what I did to my installation of uBlock to be different (as I mentioned, I didn't think I messed with the filters/list/settings at all).

Sorry for all this confusion, I've been chasing this for a while.

**Comment by uBlock-user** [comment]
> I do see a blocked entry in the logger

That filter shouldn't be applied, once you whitelist a website on uBO.

**Comment by uBlock-user** [comment]
@chrisblakley I can't reproduce that filter being applied after whitelisting.

**Comment by chrisblakley** [comment]
Here are the details on the autotrack block:
![screen shot 2018-08-16 at 10 23 39 am](https://user-images.githubusercontent.com/6349678/44214599-8bc83c00-a13e-11e8-98d7-8f54d4b8c3cb.png)

On reload (per the steps to reproduce), I do see another block entry:
![screen shot 2018-08-16 at 10 23 48 am](https://user-images.githubusercontent.com/6349678/44214620-9682d100-a13e-11e8-8cb4-5aede51ce9b5.png)

I just had a colleague test this on his machine (Chrome 68 on Mac) and had the same results as I've been seeing.

**Comment by gorhill** [comment]
Ok, it's a network request emitted by dev tools. It's context is literally the `behind-the-scene` scope, thus it won't be subject to whitelisting unless you whitelist `behind-the-scene`. This is by design.

You can use dynamic URL filtering from the logger if you want the specific network request to no longer be filtered by uBO.

**Comment by uBlock-user** [comment]
Specific to MacOS then ?

**Comment by uBlock-user** [comment]
> thus it won't be subject to whitelisting unless you whitelist behind-the-scene. 

I haven't whitelisted behind-the-scene requests, yet the filter is not applied once I whitelist the site.

**Comment by gorhill** [comment]
No, specific to Chrome: the dev tools send out network requests and these are caught by uBO as context-less (aka `behind-the-scene`) network requests. These are now filtered by uBO since a while because <https://twitter.com/gorhill/status/1030071494263615489>.

Note that in the current case I still can debug the content of `autotrack.js` in dev tools after whitelisting the site, the blocked request is that of `autotrack.js.map`, see ["Use a source map"](https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map).

**Comment by uBlock-user** [comment]
`autotrack.js.map` doesn't appear in the logger on my end, very weird.

**Comment by chrisblakley** [comment]
Thanks for the clarification- it is definitely interesting. If that is the case where uBlock is preventing a fetch from a `behind-the-scene` scope, shouldn't both fetches `(A)` and `(B)` fail? They both load autotrack.js since that resource is requested on every page of the website.

**Comment by gorhill** [comment]
> doesn't appear in the logger on my end

There is a setting "Enable JavaScript source maps" in the dev tools settings.

**Comment by gorhill** [comment]
> shouldn't both fetches (A) and (B) fail

None of them fail on my side, regardless of whether the site is whitelisted or not. The logger is what must be used to determine what is blocked or not with regard to network requests. If the logger reports as not being blocked, and there is still an error, the issue lies somewhere else.

**Comment by uBlock-user** [comment]
Done, still the name.

**Comment by chrisblakley** [comment]
I've tested in Chromium as well before, but I just tried installing uBlock on Chromium 68 and can reproduce your screenshot above. Whether uBlock is enabled or disabled on the site both fetches are successful. However, specifically in Chrome 68 with uBlock fetch `(A)` fails on my machine as well as my coworker's Mac. Could there be a difference between this in Chromium 68 and Chrome 68 (I'm not *super* familiar with Chromium myself)?

**Comment by chrisblakley** [comment]
I have also tested Chrome Canary (70) with success as well. Here is a screenshot of the behind-the-scene logger on initial pageload where it is blocking the XHR requests.

![screen shot 2018-08-16 at 11 29 02 am](https://user-images.githubusercontent.com/6349678/44218453-b9fe4980-a147-11e8-83ed-097a767f7148.png)

Let me know if that's what you were looking for or if there is something more detailed I can provide.

**Comment by gorhill** [comment]
I am not hitting that EasyList filter (which looks terrible to me re. false positives) -- maybe it was removed? Force an update of EasyList.

**Comment by chrisblakley** [comment]
I just purged all caches and also forced an update on EasyList specifically, but still having the same issue. Prior to the update, it said that it was last updated a day ago.

![screen shot 2018-08-16 at 11 57 00 am](https://user-images.githubusercontent.com/6349678/44220051-83c2c900-a14b-11e8-8ac3-b4422be14973.png)

(Added a screenshot just to compare the RegEx)

**Comment by uBlock-user** [comment]
It probably pulled from the cache then..

**Comment by gorhill** [comment]
Ok I see that filter in EasyList on my side, but the context of the network requests is `gearside.com`  on my side, so they are not being filtered since the filter applies to 3rd-party requests:

![a](https://user-images.githubusercontent.com/585534/44220929-00ef3d80-a14e-11e8-9b93-0c41e975b925.png)

What is the context on your side? (click the 4th cell in the logger -- I consider seriously adding a context column in the logger to make this information available immediately).

**Comment by gorhill** [comment]
The context in your screenshot shows as `behind-the-scene`. This means uBO is unable to determine where the network request comes from (it came from `gearside.com` in my case as shown above). 

Being unable to determine where it came from, uBO assigns an artificial context named `behind-the-scene`. As a result, everything is 3rd-party to `behind-the-scene`, and the request was blocked as a result.

The three rows are used to set dynamic URL filtering rules.

Now as to why the network request is context-less on your side, I don't know.

**Comment by chrisblakley** [comment]
The initiator on my end is the `sw.js` file.

Chrome 68:
<img width="988" alt="screen shot 2018-08-17 at 8 24 27 am" src="https://user-images.githubusercontent.com/6349678/44266034-048acf00-a1f7-11e8-9032-ef86a8e5c5fc.png">

Chrome Canary (70), for reference:
![screen shot 2018-08-17 at 8 25 31 am](https://user-images.githubusercontent.com/6349678/44266182-95fa4100-a1f7-11e8-893d-9b70ccf47aee.png)

I'm certain that the `sw.js` initiator is what would cause the context to be `behind-the-scene`, but like you mentioned, I have no idea why it'd be different for different users.

**Comment by gorhill** [comment]
`sw.js` means the initiator will be that of the worker URL -- it's supposed to be set properly.

Maybe re-open <https://bugs.chromium.org/p/chromium/issues/detail?id=834734> with you repro case?

**Comment by chrisblakley** [comment]
Just confirming that this issue has been resolved in the stable release of Chrome 71. Here is the actual bug that was causing it in Chromium:
https://bugs.chromium.org/p/chromium/issues/detail?id=884007

Thanks for helping me troubleshoot this.
