### ISSUE TITLE
uBlock + Firefox = DNS Leaking

### ISSUE THREAD

**Issue by snoitallicso** [uBlockOrigin/uBlock-issues#1743]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

**Settings**: 

Proxy DNS when using SOCKS v5 = true

Enable DNS over HTTPS = true

Provider DNS: NextDNS, Cloudflare (it doesn't matter even if it on/off) 

I'm using proxy extension to get one stricted by country website and find out that it can detect my actual IP without problem. At forums root of the problem named by DNS is leaking.

At first time I was thinking that problem can be fixed by about:config (to fix WebRTC Leaking), so I switch:

>Set these to False

>about:config?filter=media.peerconnection.enabled
>about:config?filter=media.peerconnection.use_document_iceservers
>about:config?filter=media.peerconnection.video.enabled
>about:config?filter=webgl.enable-webgl2
>Set these to True
>about:config?filter=media.peerconnection.turn.disable
>about:config?filter=webgl.disabled
>Set to 1
>about:config?filter=media.peerconnection.identity.timeout

But problem is not going away.

After that I switch over 6 proxy extensions with dozen of the countries.

But that doesn't change anything. So I started to disable extensions and check… And I solve my problem as uBlock was disabled!

I like uBlock and do not want it to change for ADBP etc. 

Can you fix that issue?

P.S. at Chrome this problem doesn't appear.

### A specific URL where the issue occurs

https://surfshark.com/dns-leak-test

### Steps to Reproduce

1. Install a proxy extension
2. Install ublock
3. Go to https://surfshark.com/dns-leak-test
4. Now disable ublock and retest

### Expected behavior

My ISP's original IP shouldn't be available for public.

### Actual behavior

Proxy IP + ISP's available for web services.

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 92.0.1 / 94.0a1 (2021-09-30) 

### Operating System and version

Windows 10

**Comment by snoitallicso** [comment]
![Enable uBlock](https://user-images.githubusercontent.com/28826339/135631232-631e3b9b-ef99-4ffa-9a46-1aa0e1ae484f.png)
![Disable uBlock](https://user-images.githubusercontent.com/28826339/135631250-13e98cf1-2a71-4375-b8d8-a6df57ae1eb7.png)

**Comment by snoitallicso** [comment]
![94a](https://user-images.githubusercontent.com/28826339/135631659-dc3fa829-4503-48aa-a3ed-6bba701da280.png)
![92](https://user-images.githubusercontent.com/28826339/135631675-31e64e33-cdf8-499f-ad47-b0971d4e03e1.png)

**Comment by gorhill** [comment]
> Install a proxy extension

That is your issue, use a system-wide proxy or disable uBO's _"Uncloak canonical names"_. When you use a proxy extension, there is no guarantee that other extensions will have their own network requests go through another proxy extension.

**Comment by snoitallicso** [comment]
> > Install a proxy extension
> 
> That is your issue, use a system-wide proxy or disable uBO's _"Uncloak canonical names"_. When you use a proxy extension, there is no guarantee that other extensions will have their own network requests go through another proxy extension -- extensions cannot affect each other.

There is no problem using proxy extension without uBlock!

**Comment by gorhill** [comment]
Disable _"Uncloak canonical names"_ and report the result.

**Comment by gorhill** [comment]
Also, be more specific:

> Install a proxy extension

Provide an exact URL to such extension.

**Comment by snoitallicso** [comment]
> Uncloak canonical names

Problem solved. Please add information inside help popup for such issues?



> Also, be more specific:
> 
> > Install a proxy extension
> 
> Provide an exact URL to such extension.

Any top proxy extension from addons.mozilla.org

**Comment by snoitallicso** [comment]
NO https://browserleaks.com/ip there problem

**Comment by gorhill** [comment]
The issue is only with proxy/vpn extensions, there is no issue with system-wide proxy/vpn.

**Comment by gorhill** [comment]
I installed [Hola Free VPN Proxy Unblocker](https://addons.mozilla.org/en-US/firefox/addon/hola-unblocker/), and when uBO does a DNS query to resolve to cnames, there is a `proxyInfo` property on the request details object.

Those per-site proxy extensions are probably using [`proxy.onRequest`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/onRequest), hence why uBO's internal DNS queries do not go through the proxy. There is no magic solution for uBO not making disabling cname-uncloaking, as the `proxyInfo` property may also exist when a there is a system-wide or browser-wide proxy configuration in effect. The issue is per-site proxying through an extension.

What I could do is add a sub setting _"Disable the uncloaking of canonical names for proxied requests"_ to avoid the kind of surprised here (the imperfect proxying when done through an extension).

**Comment by uBlock-user** [comment]
same as https://github.com/uBlockOrigin/uBlock-issues/issues/911 ?

**Comment by gorhill** [comment]
Not the same, #911 was fixed by Firefox -- the issue was uBO's DNS queries were bypassing the browser-wide settings. This is fixed.

Here the issue is uBO's DNS query not being proxied by another extension doing the proxying on-the-fly through [`proxy.onRequest()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/onRequest), which is expected as extensions can't interfere which each other's requests -- there is no way for uBO whether the proxying was done on-the-fly or not.

A solution for this would be for Firefox to indicate with a property in the `proxyInfo` object whether the proxying was done on-the-gly, in which case uBO could avoid making a DNS query.

**Comment by v00v** [comment]
There is no such issue with OpenVPN.

**Comment by krystian3w** [comment]
#2267

**Comment by mb** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1910593 isn't a fix for the DNS leak described in this bug. I verified that the leak described in this issue still occurs in Firefox Nightly 132.0a1 (2024-09-18), where Bug 1910593 is fixed. The fix in uBlock https://github.com/gorhill/uBlock/commit/d5f14ffa32a3b0ae3662bd8067dc937dc116d2cc pending for the next release is still necessary.
