### ISSUE TITLE
Separate extension ID for uBO Dev builds

### ISSUE THREAD

**Issue by mikhaelkh** [uBlockOrigin/uBlock-issues#600]
Same extension ID for Release and Dev builds has multiple flaws:
1. Can't install both Release and Dev in one Firefox profile
2. [Versioning](https://redd.it/bsxdh8): hotfixes force Release version to go over Dev version
3. There's no indication that a Dev build is used in `about:addons` or in extension itself 
 (besides `b` in version)
4. ~~It is easy to install Dev over Release. Switching back requires add-on removal.~~

In my opinion, the following course of action is the best:

* Migrate current Dev build to Release and self-distribute Release builds under old ID
* Create new extension ID and self-distribute Dev builds at GitHub under new ID

Users of current Dev build will be switched to Release builds. I think this even do more good than harm, because of (3).
Users who wish to use Dev builds will need to backup settings and install new Dev build which.

**Comment by gorhill** [comment]
I don't understand why you open an issue about this after I stated it's not something I want to do.

Declined.

**Comment by gorhill** [comment]
By the way:

> Switching back requires add-on removal

I added (and will continue to do so)  a link to install the AMO version in the Releases section.

**Comment by mikhaelkh** [comment]
> I don't understand why you open an issue about this after I stated it's not something I want to do.

I opened this because it went from "versioning suggestion" at Reddit to "same ID issue".

> users will have to backup/restore to migrate to the new extension. 

They can do nothing and will continue to get Release builds. Because of (3) some of them even don't know they're on Dev. Also you will get a signed Release builds.

> In the big picture, having versions change the way they do now is a non-issue, and keeps me free to work on more important issues.

It is not an urgent one. But it is an issue because of the reasons mentioned above.

**Comment by gorhill** [comment]
> They can do nothing and will continue to get Release builds

I am talking about users of the dev build -- if I create a new extension id, it's equivalent to a new extension, and their dev build is going to become stale and their data won't be auto-migrated to the new extension. I don't want to badger people who chose to install the dev build with new required steps to migrate all their data to move to the new extension id. Beside I like the ability to easily install either build over either ones and not requiring data migration.

**Comment by mikhaelkh** [comment]
> their dev build is going to become stale and their data won't be auto-migrated to the new extension

Their extension won't become stale, they will be switched to self-distributed Release builds and will continue to get updates.

> Beside I like the ability to easily install either build over the other one and not requiring data migration

That's one of the main reasons why beta versions were removed from AMO - problems with users switching between Release and Beta caused data corruption and loss if channels were incompatible.
Switching from Dev to Release requires add-on removal. Is the fact that extension data is not removed documented, and you can install uBO again w/o data loss, or it might change to Chrome-like behavior?

**Comment by gorhill** [comment]
> they will be switched to self-distributed Release builds

How? When I published a stable release, this does not cause dev build users to be updated to stable release -- the dev build update independently from the stable build.

> Switching from Dev to Release requires add-on removal

See <https://github.com/gorhill/uBlock/releases/tag/1.19.6> for example: installing stable from the Release  section won't cause data loss.

**Comment by mikhaelkh** [comment]
> How they will be switched to self-distributed Release builds?

Because you will switch them using [updates.json](https://raw.githubusercontent.com/gorhill/uBlock/master/dist/firefox/updates.json)
Maybe it's not worth it, It's necessary to solve (2), but with loss of ability to easily install either build over the other one and not requiring data migration.
(1) can be solved by creating another Dev with new ID and updating both Devs simultaneously.

**Comment by mikhaelkh** [comment]
@uBlock-user, add `Firefox` label, I don't have access.

> I don't want to badger people who chose to install the dev build with new required steps to migrate all their data to move to the new extension id.

Users of Dev builds should expect that extension will contain bugs and be ready to act accordingly: report bugs, backup/restore data. Besides, (4) only was resolved recently, you still can't install Release over Dev in AMO, so some users might got stuck using Dev and do not know how to migrate, there's no mention of signed Release versions in Readme.md or wiki.

@uBlock-user, @gwarser, @jspenguin2017, what do you think, is migrating Dev users to Release too radical to solve (1)-(3)? Is ability to easily install either build over the other one and not requiring data migration worth ignoring the flaws?

**Comment by uBlock-user** [comment]
> what do you think, is migrating Dev users to Release too radical to solve (1)-(3)?

I do agree with the point of being not able to install stable and dev builds simultaneously on the same Firefox profile like we can do on Chromium, but since I have never have to run those two together, I have no issue with that flaw staying in.

**Comment by jspenguin2017** [comment]
@mikhaelkh I don't maintain the Firefox build, for Chrome, the extension ID is assigned to you so you can't have two extensions with the same ID.

**Comment by mikhaelkh** [comment]
Again, emergency fix changes dev from 1.22.3b18 to 1.22.5b0

> I can't ask Mozilla to sign a uBO version that is lower than the last signed version, this causes an error and the request to sign is refused.

This clearly indicates that Mozilla doesn't want you to have multiple channels under same ID. This just creates confusion when reading wiki. For example, `extensionUpdateForceReload` appeared in 1.22.3b3, but is not present in 1.22.4.

**Comment by gwarser** [comment]
One bad side effect - sync will stop working between different ext IDs.

**Comment by gorhill** [comment]
I am declining, everything is working fine as it is, this would be a disruptive change to all those using the dev build, beside forcing me to spend time on a non-issue really.
